export const cities: string[] = [
  'alba-iulia',
  'arad',
  'pitesti',
  'bacau',
  'oradea',
  'bistrita',
  'botosani',
  'brasov-ghimbav',
  'braila',
  'buzau',
  'resita',
  'calarasi',
  'cluj-napoca',
  'constanta',
  // nu vine pe api 'covasna',
  'targoviste',
  'craiova',
  'galati',
  'giurgiu',
  'targu-jiu',
  'miercurea-ciuc',
  // nu vine pe api hunedoara,
  'slobozia',
  'iasi',
  'bucuresti-afumati',
  'baia-mare',
  'drobeta-turnu-severin',
  'targu-mures',
  'piatra-neamt',
  'slatina',
  'ploiesti',
  'satu-mare',
  'zalau',
  'sibiu',
  'suceava',
  'alexandria',
  'timisoara',
  'tulcea',
  // NEGRESTI (VASLUI),
  'ramnicu-valcea',
  'focsani',
  'bucuresti-baneasa',
  'bucuresti-filaret',
];
