export const counties: string[] = [
  'Ilfov',
  'Alba',
  'Arad',
  'Argeș',
  'Bacău',
  'Bihor',
  'Bistrița-Năsăud',
  'Botoșani',
  'Brașov',
  'Brăila',
  'Buzău',
  'Caraș-Severin',
  'Călărași',
  'Cluj',
  'Constanța',
  'Covasna',
  'Dâmbovița',
  'Dolj',
  'Galați',
  'Giurgiu',
  'Gorj',
  'Harghita',
  'Hunedoara',
  'Ialomița',
  'Iași',
  'Maramureș',
  'Mehedinți',
  'Mureș',
  'Neamț',
  'Olt',
  'Prahova',
  'Satu Mare',
  'Sălaj',
  'Sibiu',
  'Suceava',
  'Teleorman',
  'Timiș',
  'Tulcea',
  'Vaslui',
  'Vâlcea',
  'Vrancea',
];
export const cities: string[] = [
  'bucuresti-baneasa',
  'bucuresti-filaret',
  'bucuresti-afumati',
  'alba-iulia',
  'arad',
  'pitesti',
  'bacau',
  'oradea',
  'bistrita',
  'botosani',
  'brasov-ghimbav',
  'braila',
  'buzau',
  'resita',
  'calarasi',
  'cluj-napoca',
  'constanta',
  'targu-secuiesc',
  'targoviste',
  'craiova',
  'galati',
  'giurgiu',
  'targu-jiu',
  'miercurea-ciuc',
  'deva',
  'slobozia',
  'iasi',
  'baia-mare',
  'drobeta-turnu-severin',
  'targu-mures',
  'piatra-neamt',
  'slatina',
  'ploiesti',
  'satu-mare',
  'zalau',
  'sibiu',
  'suceava',
  'alexandria',
  'timisoara',
  'tulcea',
  'barlad',
  'ramnicu-valcea',
  'focsani',
];
// TODO : asign accordingly
export enum CitiesToCouties {
  'bucuresti-baneasa' = 'bucuresti',
  'bucuresti-filaret' = 'bucuresti',
  'bucuresti-afumati' = 'bucuresti',
  'alba-iulia' = 'alba',
  'arad' = 'arad',
  'pitesti' = 'arges',
  'bacau' = 'bacau',
  'oradea' = 'bihor',
  'bistrita' = 'bistrita-nasaud',
  'botosani' = 'botosani',
  'brasov-ghimbav' = 'brasov',
  'braila' = 'braila',
  'buzau' = 'buzau',
  'resita' = 'caras-severin',
  'calarasi' = 'calarasi',
  'cluj-napoca' = 'cluj',
  'constanta' = 'constanta',
  'targu-secuiesc' = 'covasna',
  'targoviste' = 'dambovita',
  'craiova' = 'dolj',
  'galati' = 'galati',
  'giurgiu' = 'giurgiu',
  'targu-jiu' = 'gorj',
  'miercurea-ciuc' = 'harghita',
  'deva' = 'hunedoara',
  'slobozia' = 'ialomita',
  'iasi' = 'iasi',
  'baia-mare' = 'maramures',
  'drobeta-turnu-severin' = 'mehedinti',
  'targu-mures' = 'mures',
  'piatra-neamt' = 'neamt',
  'slatina' = 'olt',
  'ploiesti' = 'prahova',
  'satu-mare' = 'satu-mare',
  'zalau' = 'salaj',
  'sibiu' = 'sibiu',
  'suceava' = 'suceava',
  'alexandria' = 'teleorman',
  'timisoara' = 'timisoara',
  'tulcea' = 'tulcea',
  'barlad' = 'vaslui',
  'ramnicu-valcea' = 'valcea',
  'focsani' = 'vrancea',
}
