name: PR validation CI
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Run install command
        run: npm ci --legacy-peer-deps
        
      - name: Define Env Secrets
        env: 
          apiKey: ${{ secrets.apiKey }}
          authDomain: ${{ secrets.authDomain }}
          databaseURL: ${{ secrets.databaseURL }}
          projectId : ${{ secrets.projectId }}
          storageBucket: ${{ secrets.storageBucket }}
          messagingSenderId: ${{ secrets.messagingSenderId }}
          appId: ${{ secrets.appId }}
          measurementId: ${{ secrets.measurementId }}

      - name: Run build command
        run: npm run build
