name: PR validation CI
on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Go to the correct path
        run:  cd ../

      - name: Run build command
        run:  npm run build
