name: PR validation CI
on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - uses: actions/checkout@v3
      - name: Run install command
        run: npm i

      - uses: actions/checkout@v3
      - name: Run build command
        run: npm run build
