name: PR validation CI
on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alert-app-fe
    steps:
      - name: Go to correct path folder
        run: cd --dir alert-app-fe
         
      - name: Run build command
        run:  npm run build
