name: PR validation CI
on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Run install command
        run:  npm run install

      - uses: actions/checkout@v3
      - name: Run build command
        run:  npm run build
